# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
warnings_are_errors: true

r:
  - release
  - devel
  
apt_packages:
 - libssh-dev

notifications:
    email:
    on_success: change
    on_failure: change
